project:
  type: website
  output-dir: _site
  resources:
    - "images/"
    - "files/"
    
execute:
  freeze: true  # Esto congela los resultados de la ejecución

website:
  title: "Roberto Cantillan"
  site-url: https://rcantillan.github.io
  description: "Sitio personal de Roberto Cantillan"
  favicon: "images/favicon.ico"
  
  navbar:
    background: none
    foreground: dark
    search: true
    right:
      - text: "About"
        href: about/index.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "Talks"
        href: talk/index.qmd
      - text: "Publications"
        href: publication/index.qmd
      - text: "Projects"
        href: project/index.qmd
      - icon: github
        href: https://github.com/rcantillan
  
  page-footer:
    left: |
      © 2024 Roberto Cantillan 
      Made with [Quarto](https://quarto.org)
    right: |
      [License](/license.html) 
      [Contact](/contact.html)

format:
  html:
    theme: 
      - cosmo
      - assets/custom.scss
    css: styles.css
    toc: true
    page-layout: full
    code-copy: true
    code-overflow: wrap
    mainfont: "Commissioner"
    monofont: "Fira Code"
    highlight-style: ayu-light
    grid:
      sidebar-width: 300px
      body-width: 800px
      margin-width: 300px