project:
  type: website
  output-dir: _site
  resources:
    - "images/"
    - "files/"
    
execute:
  freeze: auto

website:
  title: "Roberto Cantillan"
  site-url: https://rcantillan.github.io
  description: "Sitio personal de Roberto Cantillan"
  favicon: "images/favicon.ico"
  
  navbar:
    background: none
    foreground: dark
    logo: "img/noun-small-world-network-6148828.png"
    search: true
    right:
      - text: "About"
        href: about/index.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "Talks"
        href: talk/index.qmd
      - text: "Publications"
        href: publication/index.qmd
      - text: "Projects"
        href: project/index.qmd
      - icon: github
        href: https://github.com/rcantillan
  
  page-footer:  
    left: >-
     &#169; 2024 Roberto Cantillan &#8729; Made with [Quarto](https://quarto.org)
    center: |
      <a class="link-dark me-1" href="/accessibility.html" title="Accessibility commitment" target="_blank" rel="noopener">{{< fa universal-access >}}</a>
      <a class="link-dark me-1" href="" title="Substack" target="_blank" rel="noopener">{{< bi substack >}}</a>
      <a class="link-dark me-1" href="https://github.com/rcantillan" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
      <a class="link-dark me-1" href="https://cl.linkedin.com/in/roberto-cantillan-carrasco-67620517b" title="LinkedIn" target="_blank" rel="noopener">{{< fa brands linkedin >}}</a>
      <a class="link-dark me-1" href="https://orcid.org/0000-0003-0494-0692;" title="orcid" target="_blank" rel="noopener">{{< ai orcid >}}</a>
      <a class="link-dark me-1" href="https://scholar.google.com/citations?user=xZkAmvAAAAAJ&hl=es" title="Google Scholar" target="_blank"rel="noopener">{{< ai google-scholar >}}</a>


    right: 
      - text: "Accessibility"
        aria-label: "Accessibility Commitment"
        href: accessibility.qmd
      - text: "Contact"
        aria-label: "Contact Form"
        href: "contact.qmd"
      - text: "License"
        aria-label: "License Details"
        href: license.qmd
      - icon: rss
        href: blog/index.xml

format:
  html:
    theme:
      light: 
        - cosmo
        - assets/rober_light.scss
        - assets/rober_about.scss  # Añade esta línea
      dark:
        - cosmo
        - assets/rober_dark.scss
        - assets/rober_about.scss  # Añade esta línea
    code-link: true
    pagetitle: "{{< meta title >}}"
    lightbox: true
    toc: true                    # Habilitar tabla de contenidos
    toc-location: right          # Ubicar en la derecha
    toc-title: "En esta página"  # Título en español
    page-layout: article         # Usar layout de artículo en lugar de full
    grid:
      sidebar-width: 250px       # Ancho del sidebar
      body-width: 800px         # Ancho del contenido
      margin-width: 250px       # Ancho del margen
    include-in-header: 
      text: |
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/academicons@1.9.1/css/academicons.min.css">
      
      