project:
  type: website
  output-dir: _site

website:
  title: "Roberto Cantillan"
  site-url: https://rcantillan.github.io
  description: "Sitio web personal de Roberto Cantillan"
  navbar:
    background: none
    foreground: dark
    search: true
    right:
      - text: About
        href: about/index.qmd
      - text: Blog
        href: blog/index.qmd
      - text: Talks
        href: talk/index.qmd
      - text: Publications
        href: publication/index.qmd
      - text: Projects
        href: project/index.qmd
  page-footer:
    left: |
      © 2024 Roberto Cantillan<br>
      Hecho con [Quarto](https://quarto.org)
    right:
      - icon: github
        href: https://github.com/rcantillan
      - icon: envelope
        href: mailto:tu@email.com

format:
  html:
    theme: 
      light: [default, assets/apero-light.scss]
      dark: [default, assets/apero-dark.scss]
    css: assets/styles.css
    toc: true
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    citations-hover: true
    grid:
      sidebar-width: 300px
      body-width: 800px
      margin-width: 300px